### ISSUE TITLE
add escaped \

### ISSUE THREAD

**Issue by v-bus** [ser1us/vscode-shrug#4]
in golang code it wants to have  ¯\\\\_(ツ)_/¯

**Comment by v-bus** [comment]
"¯\\\_(ツ)_/¯"

**Comment by ser1us** [comment]
Hi there, sorry for my late response. I will have a look at it sometime next week 👍

**Comment by ser1us** [comment]
Hey @v-bus sorry for the very long wait. I finally managed to check out golang and as far as I can tell there is no need for adjustments?

```
package main

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// Main function ¯\_(ツ)_/¯
func main() {
	// Sorting the given slice
	s := []int{345, 78, 123, 10, 76, 2, 567, 5}
	sort.Ints(s)
	fmt.Println("Sorted slice: ", s)

	// Finding the index
	fmt.Println("Index value: ", strings.Index("GeeksforGeeks", "ks"))

	// Finding the time
	fmt.Println("Time: ", time.Now().Unix())

}
```

this works just fine for me. Anything else I would have to check out? Keep in mind I have no experience at all with Go :)

Cheers

**Comment by v-bus** [comment]
Hi! I tried it, not in comments like you did. I tried it in stout printing.

fmt.Println("¯\\(ツ)/¯")

According to your answer, you never thought that it could be used in that case. That's OK for me.

**Comment by ser1us** [comment]
Yes indeed. The only reason this extension exists at all is to leave funny comments ^^ 

Thanks anyway for your interest in this silly extension and have a wonderful day. I will close the issue now.
