### ISSUE TITLE
Convert /shrug to shrug ASCII

### ISSUE THREAD

**Issue by sleeyax** [ser1us/vscode-shrug#5]
Nice extension! Would it be possible to automatically convert `/shrug` to `¯\_(ツ)_/¯` (maybe when a specific key combo is pressed afterwards or make this kind of behavior configurable via settings?)

**Comment by ser1us** [comment]
Greetings and thanks 🙃

So far it has a snippet `shrug` and a shortcut (ctrl+u, ctrl+u).

May I ask where you would use this `/shrug`? Or rather how exactly? Is it inline in code/text?

**Comment by ser1us** [comment]
Ahh on second thought I think I know what you mean. Like auto expanding `/shrug` with the actual ascii art while happily typing away. 

That would be really neat, I will definitely check if that's possible 👍

**Comment by sleeyax** [comment]
Yes, it's actually a thing from discord (if you're familiar with that) where if you type /shrug followed by enter in the chatbox it would send a shrug ASCII. It got buried so deeply into my muscle memory I figured to suggest it here as a feature.

**Comment by ser1us** [comment]
After looking into it and talking to some other VSCode devs I have not found a way to achieve that, sorry. Will keep my eyes peeled.
